"""Add menu models

Revision ID: e911eb7ef82d
Revises: 
Create Date: 2025-11-10 14:36:29.398997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e911eb7ef82d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_brand_id', table_name='companies')
    op.create_foreign_key(None, 'companies', 'brands', ['brand_id'], ['id'])
    op.alter_column('operation_logs', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.drop_constraint('operation_logs_ibfk_1', 'operation_logs', type_='foreignkey')
    op.create_foreign_key(None, 'operation_logs', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'operation_logs',
        existing_comment='操作日志表',
        schema=None
    )
    op.alter_column('project_categories', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('project_categories', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否启用',
               existing_comment='是否启用（1启用/0禁用）',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index('idx_is_active', table_name='project_categories')
    op.drop_index('idx_sort_order', table_name='project_categories')
    op.drop_index('uk_category_code', table_name='project_categories')
    op.create_index(op.f('ix_project_categories_category_code'), 'project_categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_project_categories_id'), 'project_categories', ['id'], unique=False)
    op.drop_table_comment(
        'project_categories',
        existing_comment='项目类别表',
        schema=None
    )
    op.drop_index('idx_project_items_project_id', table_name='project_items')
    op.create_foreign_key(None, 'project_items', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('project_milestones', 'status',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_comment='状态：0待开始/1进行中/2已完成/3已延期/4已取消',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('project_milestones', 'is_critical',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否关键节点',
               existing_comment='是否关键节点（0否/1是）',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('project_milestones', 'is_visible_to_supplier',
               existing_type=mysql.TINYINT(display_width=1),
               comment='供应商是否可见',
               existing_comment='供应商是否可见（0否/1是）',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index('idx_planned_date', table_name='project_milestones')
    op.drop_index('idx_project_id', table_name='project_milestones')
    op.drop_index('idx_project_milestones_created_by', table_name='project_milestones')
    op.drop_index('idx_project_milestones_project_id', table_name='project_milestones')
    op.drop_index('idx_project_milestones_sort_order', table_name='project_milestones')
    op.drop_index('idx_sort_order', table_name='project_milestones')
    op.drop_index('idx_status', table_name='project_milestones')
    op.create_index(op.f('ix_project_milestones_id'), 'project_milestones', ['id'], unique=False)
    op.drop_constraint('fk_milestone_creator', 'project_milestones', type_='foreignkey')
    op.create_foreign_key(None, 'project_milestones', 'users', ['created_by'], ['id'])
    op.drop_table_comment(
        'project_milestones',
        existing_comment='项目时间节点表',
        schema=None
    )
    op.alter_column('projects', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='项目状态',
               existing_comment='项目状态(0已停止/1进行中/3竞标中/4已完成/5已取消)',
               existing_nullable=True)
    op.drop_index('idx_category_id', table_name='projects')
    op.drop_index('idx_projects_category_id', table_name='projects')
    op.drop_index('idx_projects_company_id', table_name='projects')
    op.drop_index('idx_projects_created_at', table_name='projects')
    op.drop_index('idx_projects_creator_id', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_status_created_at', table_name='projects')
    op.create_foreign_key(None, 'projects', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'project_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['creator_id'], ['id'])
    op.drop_index('idx_quotation_items_brand_id', table_name='quotation_items')
    op.drop_index('idx_quotation_items_project_item_id', table_name='quotation_items')
    op.drop_index('idx_quotation_items_quotation_id', table_name='quotation_items')
    op.create_foreign_key(None, 'quotation_items', 'quotations', ['quotation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quotation_items', 'project_items', ['project_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quotation_items', 'brands', ['brand_id'], ['id'])
    op.drop_index('idx_quotations_created_at', table_name='quotations')
    op.drop_index('idx_quotations_evaluated_by', table_name='quotations')
    op.drop_index('idx_quotations_project_id', table_name='quotations')
    op.drop_index('idx_quotations_project_supplier', table_name='quotations')
    op.drop_index('idx_quotations_status', table_name='quotations')
    op.drop_index('idx_quotations_status_submitted_at', table_name='quotations')
    op.drop_index('idx_quotations_submitted_at', table_name='quotations')
    op.drop_index('idx_quotations_supplier_id', table_name='quotations')
    op.create_foreign_key(None, 'quotations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quotations', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quotations', 'users', ['evaluated_by'], ['id'])
    op.create_foreign_key(None, 'role_permission', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permission', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_supplier_project_history_company_id', table_name='supplier_project_history')
    op.drop_index('idx_supplier_project_history_project_id', table_name='supplier_project_history')
    op.drop_index('idx_supplier_project_history_supplier_id', table_name='supplier_project_history')
    op.create_foreign_key(None, 'supplier_project_history', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'supplier_project_history', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'supplier_project_history', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('suppliers', 'company_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment='注册地址',
               existing_comment='公司地址',
               existing_nullable=True)
    op.alter_column('suppliers', 'business_scope',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='主营产品',
               existing_comment='经营范围',
               existing_nullable=True)
    op.alter_column('suppliers', 'bank_account_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=100),
               existing_comment='账户名称',
               existing_nullable=True)
    op.alter_column('suppliers', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='审核状态（-1待审核/0审核失败/1审核通过）',
               existing_comment='审核状态(-1待审核/0审核失败/1审核通过)',
               existing_nullable=True)
    op.drop_index('idx_suppliers_audit_user_id', table_name='suppliers')
    op.drop_index('idx_suppliers_created_at', table_name='suppliers')
    op.drop_index('idx_suppliers_status', table_name='suppliers')
    op.drop_index('idx_suppliers_status_created_at', table_name='suppliers')
    op.create_foreign_key(None, 'suppliers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'suppliers', 'users', ['audit_user_id'], ['id'])
    op.drop_index('idx_upload_files_category', table_name='upload_files')
    op.drop_index('idx_upload_files_created_at', table_name='upload_files')
    op.drop_index('idx_upload_files_uploader_id', table_name='upload_files')
    op.create_foreign_key(None, 'upload_files', 'users', ['uploader_id'], ['id'])
    op.create_foreign_key(None, 'user_role', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_is_superuser', table_name='users')
    op.drop_index('idx_users_phone', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_users_is_superuser', 'users', ['is_superuser'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'upload_files', type_='foreignkey')
    op.create_index('idx_upload_files_uploader_id', 'upload_files', ['uploader_id'], unique=False)
    op.create_index('idx_upload_files_created_at', 'upload_files', ['created_at'], unique=False)
    op.create_index('idx_upload_files_category', 'upload_files', ['category'], unique=False)
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.create_index('idx_suppliers_status_created_at', 'suppliers', ['status', 'created_at'], unique=False)
    op.create_index('idx_suppliers_status', 'suppliers', ['status'], unique=False)
    op.create_index('idx_suppliers_created_at', 'suppliers', ['created_at'], unique=False)
    op.create_index('idx_suppliers_audit_user_id', 'suppliers', ['audit_user_id'], unique=False)
    op.alter_column('suppliers', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='审核状态(-1待审核/0审核失败/1审核通过)',
               existing_comment='审核状态（-1待审核/0审核失败/1审核通过）',
               existing_nullable=True)
    op.alter_column('suppliers', 'bank_account_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_comment='账户名称',
               existing_nullable=True)
    op.alter_column('suppliers', 'business_scope',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment='经营范围',
               existing_comment='主营产品',
               existing_nullable=True)
    op.alter_column('suppliers', 'company_address',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment='公司地址',
               existing_comment='注册地址',
               existing_nullable=True)
    op.drop_constraint(None, 'supplier_project_history', type_='foreignkey')
    op.drop_constraint(None, 'supplier_project_history', type_='foreignkey')
    op.drop_constraint(None, 'supplier_project_history', type_='foreignkey')
    op.create_index('idx_supplier_project_history_supplier_id', 'supplier_project_history', ['supplier_id'], unique=False)
    op.create_index('idx_supplier_project_history_project_id', 'supplier_project_history', ['project_id'], unique=False)
    op.create_index('idx_supplier_project_history_company_id', 'supplier_project_history', ['company_id'], unique=False)
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.create_index('idx_quotations_supplier_id', 'quotations', ['supplier_id'], unique=False)
    op.create_index('idx_quotations_submitted_at', 'quotations', ['submitted_at'], unique=False)
    op.create_index('idx_quotations_status_submitted_at', 'quotations', ['status', 'submitted_at'], unique=False)
    op.create_index('idx_quotations_status', 'quotations', ['status'], unique=False)
    op.create_index('idx_quotations_project_supplier', 'quotations', ['project_id', 'supplier_id'], unique=False)
    op.create_index('idx_quotations_project_id', 'quotations', ['project_id'], unique=False)
    op.create_index('idx_quotations_evaluated_by', 'quotations', ['evaluated_by'], unique=False)
    op.create_index('idx_quotations_created_at', 'quotations', ['created_at'], unique=False)
    op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    op.create_index('idx_quotation_items_quotation_id', 'quotation_items', ['quotation_id'], unique=False)
    op.create_index('idx_quotation_items_project_item_id', 'quotation_items', ['project_item_id'], unique=False)
    op.create_index('idx_quotation_items_brand_id', 'quotation_items', ['brand_id'], unique=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_index('idx_projects_status_created_at', 'projects', ['status', 'created_at'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_creator_id', 'projects', ['creator_id'], unique=False)
    op.create_index('idx_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('idx_projects_company_id', 'projects', ['company_id'], unique=False)
    op.create_index('idx_projects_category_id', 'projects', ['category_id'], unique=False)
    op.create_index('idx_category_id', 'projects', ['category_id'], unique=False)
    op.alter_column('projects', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='项目状态(0已停止/1进行中/3竞标中/4已完成/5已取消)',
               existing_comment='项目状态',
               existing_nullable=True)
    op.create_table_comment(
        'project_milestones',
        '项目时间节点表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'project_milestones', type_='foreignkey')
    op.create_foreign_key('fk_milestone_creator', 'project_milestones', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_project_milestones_id'), table_name='project_milestones')
    op.create_index('idx_status', 'project_milestones', ['status'], unique=False)
    op.create_index('idx_sort_order', 'project_milestones', ['sort_order'], unique=False)
    op.create_index('idx_project_milestones_sort_order', 'project_milestones', ['sort_order'], unique=False)
    op.create_index('idx_project_milestones_project_id', 'project_milestones', ['project_id'], unique=False)
    op.create_index('idx_project_milestones_created_by', 'project_milestones', ['created_by'], unique=False)
    op.create_index('idx_project_id', 'project_milestones', ['project_id'], unique=False)
    op.create_index('idx_planned_date', 'project_milestones', ['planned_date'], unique=False)
    op.alter_column('project_milestones', 'is_visible_to_supplier',
               existing_type=mysql.TINYINT(display_width=1),
               comment='供应商是否可见（0否/1是）',
               existing_comment='供应商是否可见',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('project_milestones', 'is_critical',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否关键节点（0否/1是）',
               existing_comment='是否关键节点',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('project_milestones', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_comment='状态：0待开始/1进行中/2已完成/3已延期/4已取消',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'project_items', type_='foreignkey')
    op.create_index('idx_project_items_project_id', 'project_items', ['project_id'], unique=False)
    op.create_table_comment(
        'project_categories',
        '项目类别表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_project_categories_id'), table_name='project_categories')
    op.drop_index(op.f('ix_project_categories_category_code'), table_name='project_categories')
    op.create_index('uk_category_code', 'project_categories', ['category_code'], unique=False)
    op.create_index('idx_sort_order', 'project_categories', ['sort_order'], unique=False)
    op.create_index('idx_is_active', 'project_categories', ['is_active'], unique=False)
    op.alter_column('project_categories', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否启用（1启用/0禁用）',
               existing_comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('project_categories', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'operation_logs',
        '操作日志表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'operation_logs', type_='foreignkey')
    op.create_foreign_key('operation_logs_ibfk_1', 'operation_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.alter_column('operation_logs', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_index('idx_brand_id', 'companies', ['brand_id'], unique=False)
    # ### end Alembic commands ###
